# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='stories.Snippet'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='stories.Snippet'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
